#!/usr/bin/env bash
# Setups the repository.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

mkdir -p config

python3 -m venv venv
source venv/bin/activate

python3 -m pip install -e . --constraint requirements.txt

pip3 install selenium

mkdir neoscrapers/outputfiles
